### ISSUE TITLE
Enable cron daemon by default

### ISSUE THREAD

**Issue by shantanugoel** [shantanugoel/asus-rt-n66u-merlin#1]
Enable cron

**Comment by RMerl** [comment]
A few related notes:

1) The default location is located in RAM.  Evaluate the possibility of relocating this to jffs, else make sure to document that the user is responsible for copying his script in the cron workdir at boot time.
2) Consider possibly adding an option to enable/disable the daemon

**Comment by RMerl** [comment]
Done in commit c486ca9ac55aab9b8fe8ebf8acc505e330e38d71.
